# Generated by Django 4.1.1 on 2022-09-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_mensalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro', models.CharField(max_length=100)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
