# Generated by Django 4.1.1 on 2022-09-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_treino'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria',
            new_name='plano',
        ),
        migrations.RenameField(
            model_name='mensalidade',
            old_name='categoria',
            new_name='plano',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='dt',
        ),
    ]
