# Generated by Django 4.1.1 on 2022-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_rename_categoria_plano_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='treino',
        ),
    ]
