# Generated by Django 4.1.1 on 2022-09-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_delete_treino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalidade',
            old_name='observacoes',
            new_name='treino',
        ),
    ]
